sudo: required
dist: trusty
language: python
cache:
  directories:
    - $HOME/.theano
    - $HOME/download
    - $HOME/miniconda
before_cache:
  - rm -rf $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history
  - pip uninstall -y keras keras_applications keras_preprocessing
matrix:
    include:
        - python: 2.7
        - python: 2.7
        - python: 3.6
        - python: 2.7
        - python: 3.6
        - python: 2.7
        - python: 3.6
        - python: 2.7
        - python: 3.6
before_install:
  # code below is taken from
  # https://github.com/theochem/qcgrids/blob/master/.travis.yml
  - if test -e $HOME/miniconda/bin; then
      echo "miniconda already installed.";
      export USE_CACHE=True;
    else
      echo "Installing miniconda.";
      rm -rf $HOME/miniconda;
      mkdir -p $HOME/download;
      if [[ -d $HOME/download/miniconda.sh ]]; then rm -rf $HOME/download/miniconda.sh; fi;
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
      fi;
      export USE_CACHE=False;
    fi
install:
  - case "${TRAVIS_JOB_NUMBER:(-1)}" in
      "1") export KERAS_BACKEND="tensorflow"; export TEST_MODE="PEP8";;
      "2") export KERAS_BACKEND="tensorflow"; export TEST_MODE="INTEGRATION_TESTS";;
      "3") export KERAS_BACKEND="tensorflow"; export TEST_MODE="DOC";;
      "4") export KERAS_BACKEND="tensorflow";;
      "5") export KERAS_BACKEND="tensorflow";;
      "6") export KERAS_BACKEND="theano"; export THEANO_FLAGS="optimizer=fast_compile";;
      "7") export KERAS_BACKEND="theano"; export THEANO_FLAGS="optimizer=fast_compile";;
      "8") export KERAS_BACKEND="cntk"; export PYTHONWARNINGS="ignore";;
      "9") export KERAS_BACKEND="cntk"; export PYTHONWARNINGS="ignore";;
    esac
  - if [[ "$USE_CACHE" == "False" ]]; then
      bash $HOME/download/miniconda.sh -b -p $HOME/miniconda;
    fi
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - if [[ "$USE_CACHE" == "False" ]]; then
      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest pandas;
    fi
  - source activate test-environment
  - travis_retry pip install --only-binary=numpy,scipy numpy nose scipy matplotlib h5py theano
  - pip install keras_applications keras_preprocessing

  # run theano to let the cache have common binary files of theano
  - python -c "import theano"

  # set library path
  - export LD_LIBRARY_PATH=$HOME/miniconda/envs/test-environment/lib/:$LD_LIBRARY_PATH

  # install PIL for preprocessing tests (they are integration tests).
  - if [[ "$TEST_MODE" == "INTEGRATION_TESTS" ]] || [[ "$TEST_MODE" == "PEP8" ]]; then
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        export PIL=Pil;
      else
        export PIL=Pillow;
      fi
    fi

    # install pydot for visualization tests
  - travis_retry conda install mkl mkl-service pydot graphviz $PIL

  - pip install -e .[tests]

  # install TensorFlow (CPU version).
  - pip install tensorflow==1.9
  
  # install cntk
  - pip install cntk

  # exclude different backends to measure a coverage for the designated backend only
  - if [[ "$KERAS_BACKEND" != "tensorflow" ]]; then
      echo '    keras/backend/tensorflow_backend.py' >> .coveragerc;
    fi
  - if [[ "$KERAS_BACKEND" != "theano" ]]; then
      echo '    keras/backend/theano_backend.py' >> .coveragerc;
    fi
  - if [[ "$KERAS_BACKEND" != "cntk" ]]; then
      echo '    keras/backend/cntk_backend.py' >> .coveragerc;
    fi

  # detect whether core files are changed or not
  - export CORE_CHANGED=False;
  - for entry in `git diff --name-only HEAD~1`; do if [[ "$entry" == "keras/backend/"* ]] || [[ "$entry" == "keras/engine/"* ]] || [[ "$entry" == "keras/layers/"* ]]; then export CORE_CHANGED=True; fi; done
  - export APP_CHANGED=False;
  - for entry in `git diff --name-only HEAD~1`; do if [[ "$entry" == "keras/applications/"* ]]; then export APP_CHANGED=True; fi; done

  #install open mpi
  - rm -rf ~/mpi
  - mkdir ~/mpi
  - pushd ~/mpi
  - wget http://cntk.ai/PythonWheel/ForKeras/depends/openmpi_1.10-3.zip
  - unzip ./openmpi_1.10-3.zip
  - sudo dpkg -i openmpi_1.10-3.deb
  - popd

# command to run tests
script:
  - export MKL_THREADING_LAYER="GNU"
  # run keras backend init to initialize backend config
  - python -c "import keras.backend"
  # create dataset directory to avoid concurrent directory creation at runtime
  - mkdir ~/.keras/datasets
  # set up keras backend
  - sed -i -e 's/"backend":[[:space:]]*"[^"]*/"backend":\ "'$KERAS_BACKEND'/g' ~/.keras/keras.json;
  - echo -e "Running tests with the following config:\n$(cat ~/.keras/keras.json)"
  - if [[ "$TEST_MODE" == "INTEGRATION_TESTS" ]]; then
      PYTHONPATH=$PWD:$PYTHONPATH py.test tests/integration_tests;
    elif [[ "$TEST_MODE" == "PEP8" ]]; then
      PYTHONPATH=$PWD:$PYTHONPATH py.test --pep8 -m pep8 -n0;
    elif [[ "$TEST_MODE" == "DOC" ]]; then
      PYTHONPATH=$PWD:$PYTHONPATH py.test tests/test_documentation.py;
    else
      PYTHONPATH=$PWD:$PYTHONPATH py.test tests/ --ignore=tests/integration_tests --ignore=tests/test_documentation.py --ignore=tests/keras/legacy/layers_test.py --cov-config .coveragerc --cov=keras tests/;
    fi
